name: unified_notifications
description: "Unified notification SDK for Flutter using FCM, APNs and MQTT (EMQX)."
version: 1.0.1
homepage: https://github.com/henry001m/unified_notifications
repository: https://github.com/henry001m/unified_notifications.git

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  firebase_core: ^3.0.0
  firebase_messaging: ^15.1.1
  flutter_local_notifications: ^19.4.0
  mqtt_client: ^10.11.1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
